export const ADD_INGREDIENS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const FETCH_DATA_FROM_SERVER = "FETCH_DATA_FROM_SERVER";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILURE = "PURCHASE_BURGER_FAILURE";
